# Generated by Django 4.2.4 on 2023-08-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='SecretWord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=6)),
            ],
            options={
                'db_table': 'secret_words',
            },
        ),
    ]
